swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
/user/transactions:
get:
  tags:
  - "transactions"
  summary: "Returns all transactions"
  description: "Returns a list of all transactions made by user"
  operationId: "getTransaction"
  produces:
  - "application/json"
  parameters: []
  responses:
    "200":
      description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int32"
      security:
      - api_key: []