swagger: "2.0"
info:
  description: "This is a sample server for Argent Bank."
  version: "1.0.0"
  title: "Swagger Argent Bank"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@argentbank.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3001"
basePath: "/api/v1"
schemes:
- "http"
paths:
  /user/transactions:
    post:
      tags:
      - "User Transactions"
      summary: "Get all transactions for the current month"
      description: "Get all transactions for the current month"
      operationId: "getTransactions"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        description: "Attach Bearer JWT"
        type: "string"
        required: true
      responses:
        '200':
          description: "User profile retrieved successully"
          schema:
            $ref: '#/definitions/MonthlyTransactions'
        '400':
          description: "Invalid Fields"
        '500':
          description: "Internal Server Error"
  /user/transactions/{id}:    
    post:
      tags:
      - "User Transactions"
      summary: "get a single transaction"
      description: "Get informations about a single transaction"
      operationId: "getTransaction"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        description: "Attach Bearer JWT"
        type: "string"
        required: true
      - in: "path"
        name: "id"
        description: "The id that needs to be fetched"
        required: true
        type: "integer"
      responses:
        '200':
          description: "Transaction retrieved successully"
          schema:
            $ref: "#/definitions/Transaction"
        '400':
          description: "Invalid Fields"
        '500':
          description: "Internal Server Error"
    put:
      security:
        - Bearer: []
      tags:
      - "User Transactions"
      summary: "Update an existing transaction"
      description: ""
      operationId: "updateTransaction"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        description: "Attach Bearer JWT"
        type: "string"
        required: true
      - in: "path"
        name: "id"
        description: "The id that needs to be fetched"
        required: true
        type: "integer"  
      - in: "body"
        name: "body"
        description: "Transaction attributes that need updates"
        required: true
        schema:
          $ref: "#/definitions/Transaction"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Transaction not found"
        "405":
          description: "Validation exception"

  
    
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  MonthlyTransactions:
    type: "object"
    properties:
      transactions:
        type: "object"
  Transaction:
    type: "object"
    properties:
      id:
        type: "integer"
      sum:
        type: "integer"
      label:
        type: "string"
      location:
        type: "string"
      date:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"